'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Reports.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to clear this query?.
        '''</summary>
        Friend ReadOnly Property ConfirmClear() As String
            Get
                Return ResourceManager.GetString("ConfirmClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to build connection string:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property ErrConnectionString() As String
            Get
                Return ResourceManager.GetString("ErrConnectionString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to create DataLinks.
        '''
        '''Please check that oledb32.dll is properly installed and registered.
        '''
        '''(the usual location is c:\Program Files\Common Files\System\Ole DB\oledb32.dll)..
        '''</summary>
        Friend ReadOnly Property ErrDataLinks() As String
            Get
                Return ResourceManager.GetString("ErrDataLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to retrieve data:
        '''Failed to retrieve data:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property ErrGettingData() As String
            Get
                Return ResourceManager.GetString("ErrGettingData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property interop_msdasc() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("interop_msdasc", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to retrieve the data:
        '''{0}.
        '''</summary>
        Friend ReadOnly Property SqlCheckFailed() As String
            Get
                Return ResourceManager.GetString("SqlCheckFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The SQL syntax has been verified against the data source..
        '''</summary>
        Friend ReadOnly Property SqlCheckSucceeded() As String
            Get
                Return ResourceManager.GetString("SqlCheckSucceeded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stored Procedures.
        '''</summary>
        Friend ReadOnly Property StoredProcedures() As String
            Get
                Return ResourceManager.GetString("StoredProcedures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tables.
        '''</summary>
        Friend ReadOnly Property Tables() As String
            Get
                Return ResourceManager.GetString("Tables", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Views.
        '''</summary>
        Friend ReadOnly Property Views() As String
            Get
                Return ResourceManager.GetString("Views", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
